import type { IconName } from './generated';

/**
 * Suchwörter je Icon für den Icon-Picker der Verwaltung (Produkte,
 * Kategorien). Kleingeschrieben, ohne den Namen selbst zu wiederholen —
 * der wird ohnehin durchsucht.
 */
export const iconKeywords: Readonly<Record<IconName, { readonly de: readonly string[]; readonly en: readonly string[] }>> = {
  /* ---------- Speisen & Getränke ---------- */
  beer: { de: ['bier', 'pils', 'weizen', 'radler', 'helles', 'maß', 'krug'], en: ['lager', 'pint', 'mug', 'ale'] },
  wine: { de: ['wein', 'rotwein', 'weißwein', 'schorle', 'sekt', 'glas'], en: ['red wine', 'white wine', 'glass', 'spritzer'] },
  shot: { de: ['schnaps', 'kurzer', 'likör', 'obstler', 'stamperl'], en: ['shot glass', 'liquor', 'spirits', 'cocktail'] },
  soda: { de: ['limo', 'limonade', 'cola', 'spezi', 'saft', 'becher', 'strohhalm'], en: ['lemonade', 'cola', 'soft drink', 'cup', 'straw'] },
  water: { de: ['wasser', 'sprudel', 'mineralwasser', 'tropfen'], en: ['drop', 'mineral water', 'still'] },
  bottle: { de: ['flasche', 'schorle', 'apfelschorle', 'saft', 'mehrweg'], en: ['juice', 'spritzer', 'returnable'] },
  coffee: { de: ['kaffee', 'tee', 'tasse', 'cappuccino', 'heißgetränk'], en: ['tea', 'cup', 'mug', 'hot drink'] },
  cake: { de: ['kuchen', 'torte', 'gebäck', 'geburtstag', 'dessert'], en: ['pastry', 'birthday', 'dessert', 'tart'] },
  sausage: { de: ['wurst', 'bratwurst', 'currywurst', 'grillwurst', 'würstchen', 'fleisch'], en: ['bratwurst', 'hot dog', 'grill', 'meat'] },
  bread: { de: ['brot', 'brötchen', 'semmel', 'brezel', 'toast', 'gebäck', 'croissant'], en: ['bun', 'roll', 'pretzel', 'toast', 'loaf', 'bakery', 'croissant'] },
  fries: { de: ['pommes', 'pommes frites', 'fritten', 'beilage'], en: ['french fries', 'chips', 'side', 'snack'] },
  icecream: { de: ['eis', 'eiskugel', 'waffel', 'softeis'], en: ['ice cream', 'cone', 'gelato'] },
  utensils: { de: ['essen', 'speisen', 'besteck', 'gabel', 'messer', 'gericht', 'menü'], en: ['food', 'meal', 'cutlery', 'fork', 'knife', 'dish'] },
  flame: { de: ['grill', 'feuer', 'scharf', 'steak', 'heiß'], en: ['fire', 'hot', 'spicy', 'barbecue', 'grilled'] },
  leaf: { de: ['blatt', 'salat', 'vegetarisch', 'vegan', 'gemüse', 'bio'], en: ['salad', 'vegetarian', 'vegan', 'vegetables', 'organic'] },
  chef: { de: ['koch', 'küche', 'kochmütze', 'senden', 'zubereitung'], en: ['cook', 'kitchen', 'toque', 'prepare'] },
  deposit: { de: ['pfand', 'rückgabe', 'mehrweg', 'becherpfand', 'kreislauf'], en: ['refund', 'return', 'reusable', 'recycle'] },

  /* ---------- Aktionen ---------- */
  cart: { de: ['warenkorb', 'einkaufswagen', 'bestellung'], en: ['basket', 'shopping cart', 'order'] },
  'cart-plus': { de: ['in den warenkorb', 'hinzufügen', 'bestellen'], en: ['add to cart', 'add', 'order'] },
  plus: { de: ['hinzufügen', 'mehr', 'neu', 'plus'], en: ['add', 'more', 'new', 'increase'] },
  minus: { de: ['weniger', 'abziehen', 'minus'], en: ['less', 'decrease', 'subtract'] },
  x: { de: ['schließen', 'abbrechen', 'entfernen', 'kreuz'], en: ['close', 'cancel', 'remove', 'cross'] },
  check: { de: ['häkchen', 'bestätigen', 'erledigt', 'ok'], en: ['tick', 'confirm', 'done', 'ok'] },
  'chevron-down': { de: ['pfeil runter', 'aufklappen', 'menü'], en: ['arrow down', 'expand', 'dropdown'] },
  'chevron-up': { de: ['pfeil hoch', 'zuklappen'], en: ['arrow up', 'collapse'] },
  'chevron-right': { de: ['pfeil rechts', 'weiter', 'öffnen'], en: ['arrow right', 'next', 'open'] },
  'chevron-left': { de: ['pfeil links', 'zurück'], en: ['arrow left', 'back', 'previous'] },
  'arrow-right': { de: ['pfeil', 'weiter', 'bestätigen', 'los'], en: ['arrow', 'next', 'continue', 'go'] },
  search: { de: ['suche', 'suchen', 'lupe', 'finden'], en: ['find', 'magnifier', 'lookup'] },
  filter: { de: ['filter', 'trichter', 'eingrenzen'], en: ['funnel', 'narrow'] },
  edit: { de: ['bearbeiten', 'stift', 'ändern'], en: ['pencil', 'change', 'modify'] },
  trash: { de: ['papierkorb', 'löschen', 'mülleimer', 'entfernen'], en: ['delete', 'bin', 'remove', 'garbage'] },
  more: { de: ['mehr', 'menü', 'weitere aktionen', 'punkte'], en: ['menu', 'more actions', 'ellipsis', 'dots'] },
  send: { de: ['senden', 'abschicken', 'to-go', 'mitnehmen', 'papierflieger'], en: ['submit', 'takeaway', 'paper plane'] },
  print: { de: ['drucken', 'bon drucken', 'ausdrucken'], en: ['printout', 'receipt'] },
  download: { de: ['herunterladen', 'export', 'speichern'], en: ['export', 'save'] },
  refresh: { de: ['aktualisieren', 'neu laden', 'wiederholen'], en: ['reload', 'retry', 'sync'] },
  split: { de: ['teilen', 'rechnung teilen', 'aufteilen', 'getrennt zahlen'], en: ['split bill', 'divide', 'separate'] },
  percent: { de: ['prozent', 'rabatt', 'nachlass', 'aktion'], en: ['discount', 'sale', 'rebate'] },
  backspace: { de: ['löschen', 'rücktaste', 'zurück löschen'], en: ['delete', 'erase', 'back'] },
  lock: { de: ['schloss', 'sperren', 'gesperrt', 'sicher'], en: ['locked', 'secure', 'padlock'] },
  eye: { de: ['auge', 'anzeigen', 'vorschau', 'sichtbar'], en: ['view', 'preview', 'visible', 'show'] },
  logout: { de: ['abmelden', 'ausloggen', 'verlassen'], en: ['sign out', 'log out', 'exit'] },
  star: { de: ['stern', 'favorit', 'favoriten', 'beliebt'], en: ['favorite', 'favourite', 'popular', 'rating'] },
  history: { de: ['verlauf', 'bestellverlauf', 'zuletzt', 'chronik'], en: ['order history', 'recent', 'past'] },
  undo: { de: ['rückgängig', 'storno', 'stornieren', 'zurücknehmen'], en: ['revert', 'cancel', 'void'] },
  copy: { de: ['kopieren', 'duplizieren', 'doppeln'], en: ['duplicate', 'clone'] },
  rotate: { de: ['drehen', 'rotieren', 'im uhrzeigersinn'], en: ['turn', 'clockwise'] },
  'zoom-in': { de: ['vergrößern', 'zoomen', 'heranzoomen'], en: ['enlarge', 'magnify', 'zoom'] },
  'zoom-out': { de: ['verkleinern', 'herauszoomen'], en: ['shrink', 'zoom'] },

  /* ---------- Zahlung & Beleg ---------- */
  card: { de: ['karte', 'ec-karte', 'kreditkarte', 'kartenzahlung'], en: ['credit card', 'debit card', 'payment'] },
  cash: { de: ['bar', 'bargeld', 'geldschein', 'barzahlung'], en: ['money', 'banknote', 'bill'] },
  contactless: { de: ['kontaktlos', 'nfc', 'karte auflegen', 'terminal'], en: ['nfc', 'tap to pay', 'terminal'] },
  ticket: { de: ['bon', 'gutschein', 'rabatt', 'eintrittskarte', 'coupon'], en: ['voucher', 'coupon', 'discount'] },
  receipt: { de: ['beleg', 'quittung', 'kassenbon', 'kassieren', 'rechnung'], en: ['bill', 'invoice', 'checkout'] },
  qr: { de: ['qr-code', 'scannen', 'code'], en: ['qr code', 'scan', 'code'] },
  tag: { de: ['preisschild', 'etikett', 'preis', 'kategorie'], en: ['price tag', 'label', 'price', 'category'] },
  drawer: { de: ['kassenlade', 'kasse', 'schublade', 'geldlade'], en: ['cash drawer', 'till', 'register'] },

  /* ---------- Betrieb ---------- */
  table: { de: ['tisch', 'tischnummer', 'platz', 'eckig'], en: ['table number', 'seat', 'rectangular'] },
  'table-round': { de: ['runder tisch', 'tisch rund', 'stehtisch', 'plätze'], en: ['round table', 'seats'] },
  users: { de: ['personen', 'gäste', 'team', 'mitglieder', 'gruppe'], en: ['people', 'guests', 'team', 'members', 'group'] },
  user: { de: ['person', 'benutzer', 'konto', 'profil'], en: ['person', 'account', 'profile'] },
  clock: { de: ['uhr', 'zeit', 'uhrzeit', 'dauer', 'warten'], en: ['time', 'duration', 'wait'] },
  calendar: { de: ['kalender', 'datum', 'termin', 'veranstaltung'], en: ['date', 'event', 'schedule'] },
  dashboard: { de: ['übersicht', 'startseite', 'kacheln'], en: ['overview', 'home', 'tiles'] },
  orders: { de: ['bestellungen', 'aufträge', 'liste'], en: ['order list', 'tickets'] },
  box: { de: ['paket', 'lager', 'bestand', 'karton', 'produkt'], en: ['package', 'inventory', 'stock', 'product'] },
  device: { de: ['gerät', 'tablet', 'handy', 'kasse'], en: ['tablet', 'phone', 'mobile'] },
  printer: { de: ['drucker', 'bondrucker', 'küchendrucker'], en: ['receipt printer', 'kitchen printer'] },
  pin: { de: ['ort', 'standort', 'adresse', 'markierung'], en: ['location', 'place', 'address', 'marker'] },
  chart: { de: ['diagramm', 'statistik', 'auswertung', 'umsatz'], en: ['statistics', 'report', 'analytics', 'sales'] },
  sliders: { de: ['einstellungen', 'optionen', 'regler', 'anpassen'], en: ['settings', 'options', 'adjust'] },
  home: { de: ['haus', 'start', 'startseite'], en: ['house', 'start'] },
  grid: { de: ['raster', 'kacheln', 'nummernblock', 'ziffern'], en: ['tiles', 'keypad', 'numbers'] },
  list: { de: ['liste', 'aufzählung', 'tische'], en: ['items', 'bullets', 'tables'] },
  note: { de: ['notiz', 'dokument', 'hinweis', 'anmerkung'], en: ['document', 'memo', 'comment'] },
  bell: { de: ['glocke', 'benachrichtigung', 'fertig', 'servieren'], en: ['notification', 'ready', 'serve', 'alert'] },
  mail: { de: ['e-mail', 'brief', 'nachricht', 'post'], en: ['email', 'letter', 'message'] },
  map: { de: ['karte', 'tischplan', 'lageplan', 'raumplan', 'grundriss'], en: ['floor plan', 'layout', 'plan'] },
  stage: { de: ['bühne', 'vorhang', 'musik', 'band'], en: ['curtain', 'music', 'band'] },
  wall: { de: ['wand', 'mauer', 'trennwand', 'ziegel'], en: ['brick', 'partition', 'barrier'] },
  text: { de: ['text', 'beschriftung', 'schrift', 'bezeichnung'], en: ['label', 'type', 'caption'] },

  /* ---------- Status ---------- */
  'check-circle': { de: ['erfolg', 'bezahlt', 'erledigt', 'abgeschlossen'], en: ['success', 'paid', 'done', 'complete'] },
  'x-circle': { de: ['fehler', 'abgelehnt', 'storniert', 'fehlgeschlagen'], en: ['error', 'declined', 'cancelled', 'failed'] },
  alert: { de: ['warnung', 'achtung', 'hinweis', 'gefahr'], en: ['warning', 'caution', 'danger'] },
  info: { de: ['information', 'hilfe', 'hinweis'], en: ['information', 'help', 'hint'] },
  wifi: { de: ['wlan', 'online', 'verbindung', 'netz'], en: ['wireless', 'online', 'connection', 'network'] },
  'wifi-off': { de: ['offline', 'keine verbindung', 'getrennt'], en: ['offline', 'no connection', 'disconnected'] },
  shield: { de: ['schutz', 'tse', 'sicherheit', 'signiert', 'fiskal'], en: ['security', 'protected', 'signed', 'fiscal'] },
};
